// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class TemperaturesByCountry : MonoBehaviour
{
    public class Row
    {
        public string dt;
        public string AverageTemperature;
        public string AverageTemperatureUncertainty;
        public string Country;

    }

    public TextAsset file;
    void Awake()
    {
        Load(file);

        //Debug.Log(Find_Temperature_By_Year_Country("1999-08-01", "Germany").AverageTemperature);
    }

    static List<Row> rowList = new List<Row>();
    bool isLoaded = false;

    public bool IsLoaded()
    {
        return isLoaded;
    }

    public List<Row> GetRowList()
    {
        return rowList;
    }

    public void Load(TextAsset csv)
    {
        rowList.Clear();
        string[][] grid = CsvParser2.Parse(csv.text);
        for (int i = 1; i < grid.Length; i++)
        {
            Row row = new Row();
            row.dt = grid[i][0];
            row.AverageTemperature = grid[i][1];
            row.AverageTemperatureUncertainty = grid[i][2];
            row.Country = grid[i][3];

            rowList.Add(row);
        }
        isLoaded = true;
    }

    public int NumRows()
    {
        return rowList.Count;
    }

    public Row GetAt(int i)
    {
        if (rowList.Count <= i)
            return null;
        return rowList[i];
    }

    public Row Find_dt(string find)
    {
        return rowList.Find(x => x.dt == find);
    }
    public List<Row> FindAll_dt(string find)
    {
        return rowList.FindAll(x => x.dt == find);
    }
    public Row Find_AverageTemperature(string find)
    {
        return rowList.Find(x => x.AverageTemperature == find);
    }
    public List<Row> FindAll_AverageTemperature(string find)
    {
        return rowList.FindAll(x => x.AverageTemperature == find);
    }
    public Row Find_AverageTemperatureUncertainty(string find)
    {
        return rowList.Find(x => x.AverageTemperatureUncertainty == find);
    }
    public List<Row> FindAll_AverageTemperatureUncertainty(string find)
    {
        return rowList.FindAll(x => x.AverageTemperatureUncertainty == find);
    }
    public Row Find_Country(string find)
    {
        return rowList.Find(x => x.Country == find);
    }
    public List<Row> FindAll_Country(string find)
    {
        return rowList.FindAll(x => x.Country == find);
    }
    public static Row Find_Temperature_By_Year_Country(string find, string country)
    {
        return rowList.Find(x => x.dt == find && x.Country == country);
    }
}